# EgyMonuments.com Scraper

In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (4.41.0)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from selenium) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trio<1.0,>=0.31.0->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trio<1.0,>=0.31.0->selenium) (3.10)
Requirement already satisfied: outcome in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (3.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\5g\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: C:\Users\5g\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException, TimeoutException

## Step 1

In [3]:
options = Options()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
# options.add_argument("--headless=new")
options.add_argument("--window-size=1920,1080")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--disable-gpu")

driver = webdriver.Chrome(options=options)
wait = WebDriverWait(driver, 15)

all_sites = []

driver.get("https://egymonuments.com/locations")

wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#portfolio > div > div > div:nth-child(1)")))
time.sleep(1)

i = 1
while True:
    try:
        item = driver.find_element(By.CSS_SELECTOR, f"#portfolio > div > div > div:nth-child({i})")
    except NoSuchElementException:
        print("Finished — no more items.")
        break

    try:
        place_name = item.find_element(By.CSS_SELECTOR, "div.p-2.w-100").text.strip()
    except NoSuchElementException:
        place_name = ""

    try:
        place_location = item.find_element(By.CSS_SELECTOR, "div.itemlocation").text.strip()
    except NoSuchElementException:
        place_location = ""

    try:
        figure = item.find_element(By.TAG_NAME, "figure")
        style = figure.get_attribute("style") or ""
        match = re.search(r"url\(['\"]?(.*?)['\"]?\)", style)
        photo_url = match.group(1) if match else ""
    except NoSuchElementException:
        photo_url = ""

    try:
        detail_link = item.find_element(By.TAG_NAME, "a").get_attribute("href")
    except NoSuchElementException:
        detail_link = ""

    print(i, "-", place_name, "|", place_location, "|", detail_link)

    all_sites.append({
        "place_name": place_name,
        "place_location": place_location,
        "photo_url": photo_url,
        "detail_link": detail_link,
    })

    i += 1

print("all_sites:", len(all_sites))

1 - Giza plateau | Giza | https://egymonuments.com/details/Pyramids
2 - Egyptian Museum | Cairo | https://egymonuments.com/details/EgyptianMuseum
3 - Sharm El Sheikh Museum | Sharm El Sheikh | https://egymonuments.com/details/SharmElSheikhMuseum
4 - Hurghada Museum | Hurghada | https://egymonuments.com/details/HurghadaMuseum
5 - Luxor Temple | Luxor | https://egymonuments.com/details/LuxorTemple
6 - Karnak Temple | Luxor | https://egymonuments.com/details/KarnakTemple
7 - Hatshepsut Temple | Luxor | https://egymonuments.com/details/HatshepsutTemple
8 - Abu Simbel Temple | Abu Simbel | https://egymonuments.com/details/AbuSimbelTemple
9 - Coptic Museum | Cairo | https://egymonuments.com/details/CopticMuseum
10 - Dandarah Temple | Qena | https://egymonuments.com/details/DandarahTemple
11 - Deir El Madina | Luxor | https://egymonuments.com/details/DeirElMadinaTemple
12 - Valley Of Kings | Luxor | https://egymonuments.com/details/ValleyOfKings
13 - Luxor Museum | Luxor | https://egymonuments.com/details/LuxorMuseum
14 - Esna Temple | Esna | https://egymonuments.com/details/EsnaTemple
15 - Salah Eldin Citadel | Cairo | https://egymonuments.com/details/SalahEldinCitadel
16 - Medinet Habu | Luxor | https://egymonuments.com/details/MedinetHabu
17 - Philae Temple | Aswan | https://egymonuments.com/details/PhilaeTemple
18 - Kom Ombo Temple | Aswan | https://egymonuments.com/details/KomOmboTemple
19 - Mummification museum | Luxor | https://egymonuments.com/details/MummificationMuseumLuxor
20 - Ramesseum | Luxor | https://egymonuments.com/details/Ramesseum
21 - Saqqara Monuments | Giza | https://egymonuments.com/details/SaqqaraMonuments
22 - The Temple Of Horus | Edfu | https://egymonuments.com/details/TheTempleOfHorusAtEdfu
23 - Tombs Of The Nobles | Luxor | https://egymonuments.com/details/TombsOfTheNobles
24 - Unfinished Obelisk | Aswan | https://egymonuments.com/details/UnfinishedObelisk
25 - Valley Of The Queens | Luxor | https://egymonuments.com/details/ValleyOfTheQueens
26 - Islamic art museum | Cairo | https://egymonuments.com/details/IslamicMuseum
27 - Baron Empain Palace | Cairo | https://egymonuments.com/details/BaronEmpainPalace
28 - Nubia Museum | Aswan | https://egymonuments.com/details/NubiaMuseum
29 - Serapeum of Alexandria | Alexandria | https://egymonuments.com/details/SerapeumofAlexandria
30 - Catacombs | Alexandria | https://egymonuments.com/details/KomelShoqafaCatacombs
31 - Alexandria National Museum | Alexandria | https://egymonuments.com/details/AlexandriaNationalMuseum
32 - Qaitbay Citadel | Alexandria | https://egymonuments.com/details/CitadelofQaitbay
33 - Ancient Roman Theatre | Alexandria | https://egymonuments.com/details/RomanAmphitheatre
34 - Royal Jewellery Museum | Alexandria | https://egymonuments.com/details/RoyalJewelleryMuseum
35 - Carter House | Luxor | https://egymonuments.com/details/CarterHouse
36 - Mernpetah | Luxor | https://egymonuments.com/details/Merenptah
37 - Deir El-shelwit | Luxor | https://egymonuments.com/details/DeirEl-shelwit
38 - Dahshur | Giza | https://egymonuments.com/details/Dahshur
39 - Memphis | Giza | https://egymonuments.com/details/Memphis
40 - Prince Mohamed Aly Palace | Cairo | https://egymonuments.com/details/PrinceMohamedAliPalace
41 - National Museum of Egyptian Civilization | Cairo | https://egymonuments.com/nmec
42 - Royal Chariots Museum | Cairo | https://egymonuments.com/details/RoyalChariotsMuseum
43 - Graeco-Roman Museum | Alexandria | https://egymonuments.com/details/GraecoRomanMuseum
44 - Temple Of Amada | Aswan | https://egymonuments.com/details/TempleOfAmada
45 - Temple Of Wadi El-Sebua | Aswan | https://egymonuments.com/details/TempleOfWadiEl-Sebua
46 - Temple of Kalabsha | Aswan | https://egymonuments.com/details/TempleofKalabsha
47 - Elmoez street | Cairo | https://egymonuments.com/details/Elmoezstreet
48 - Bab Zuwaila | Cairo | https://egymonuments.com/details/BabZuweila
49 - House of suhaym | Cairo | https://egymonuments.com/details/Houseofsuhaym
50 - Wasila Historical House | Cairo | https://egymonuments.com/details/Wasilahouse
51 - House of al-Harawy | Cairo | https://egymonuments.com/details/Elharawy
52 - Sabiel Nafesa Al-Bayda | Cairo | https://egymonuments.com/details/SabielOfNafesa
53 - Gamal El-Din El-Zahabi house | Cairo | https://egymonuments.com/details/Gamaleldin
54 - Al Ghuri Dome | Cairo | https://egymonuments.com/details/AlGhuriDome
55 - Wikala Of Al-Guri | Cairo | https://egymonuments.com/details/WikalaOfAl-Guri
56 - Gayer Anderson Museum | Cairo | https://egymonuments.com/details/GayerAndersonMuseum
57 - Elkab Tombs | Aswan | https://egymonuments.com/details/ElkabTombs
58 - Samaan Monastery | Aswan | https://egymonuments.com/details/SamaanMonastery
59 - Air Dome | Aswan | https://egymonuments.com/details/AirDome
60 - Elephantine Island | Aswan | https://egymonuments.com/details/ElephantineIsland
61 - Sehel Island | Aswan | https://egymonuments.com/details/SehelIsland
62 - The Pyramids of Meidum | Beni Suef | https://egymonuments.com/details/ThePyramidsofMeidum
63 - Fraser Tombs | Minya | https://egymonuments.com/details/FraserTombs
64 - Zawyet Sultan | Minya | https://egymonuments.com/details/ZawyetSultan
65 - Amarna | Minya | https://egymonuments.com/details/Amarna
66 - Malawy Museum | Minya | https://egymonuments.com/details/MalawyMuseum
67 - Meir Monumental Tombs | Assuit | https://egymonuments.com/details/MeirMonumentalTombs
68 - El Hawawish | Sohag | https://egymonuments.com/details/ElHawawish
69 - Merit Amun Temple | Sohag | https://egymonuments.com/details/MeritAmunTemple
70 - Sohag National Museum | Sohag | https://egymonuments.com/details/SohagNationalMuseum
71 - Sheikh Hamad Area | Sohag | https://egymonuments.com/details/ElSheikhHamad
72 - Abydos Temple | Sohag | https://egymonuments.com/details/AbydosTemple
73 - Shunet El Zebib | Sohag | https://egymonuments.com/details/ShunetElZebib
74 - Prince Youssef Palace | Qena | https://egymonuments.com/details/PrinceYoussefPalace
75 - Suez canal Museum | Ismailia | https://egymonuments.com/details/SuezcanalMuseum
76 - Beni Hassan Tomb | Minya | https://egymonuments.com/details/BeniHassanTomb
77 - Mosque- Madrassa Sultan Hassan | Cairo | https://egymonuments.com/details/Mosque-MadrassaSultanHassan
78 - El Assasif | Luxor | https://egymonuments.com/details/ElAssasif
79 - Tomb of pabasa | Luxor | https://egymonuments.com/details/Tombofpabasa
80 - El-Tod Temple | Luxor | https://egymonuments.com/details/El-TodTemple
81 - Al-Mualla Tombs | Luxor | https://egymonuments.com/details/AlMualla
82 - Mut Temple | Luxor | https://egymonuments.com/details/MutTemple
83 - Gebel al-Silsila | Aswan | https://egymonuments.com/details/Gebelal-Silsila
84 - Alhammamya Tombs | Assuit | https://egymonuments.com/details/AlhammamyaTombs
85 - Tuna el-Gebel | Minya | https://egymonuments.com/details/Tunael-Gebel
86 - Mary's Tree | Cairo | https://egymonuments.com/details/Mary%27sTree
87 - Al Matariyyah Obelisk | Cairo | https://egymonuments.com/details/AlMatariyyahObelisk
88 - Rawda Island Nilometer | Cairo | https://egymonuments.com/details/RawdaIslandNilometer
89 - Rosetta City Monuments | El-bahira | https://egymonuments.com/details/RosettaCityMonuments
90 - Kafr al-Sheikh Museum | kafr el-shiekh | https://egymonuments.com/details/KafrElshaikh
91 - Tanis (San al-Hagar) | Al-Sharqia | https://egymonuments.com/details/Tanis%28Sanal-Hagar%29
92 - Grand Egyptian Museum | Giza | https://visit-gem.com/
93 - Temple of Aghurmi in Siwa | Siwa | https://egymonuments.com/details/TempleofAghurmiinSiwa
94 - Tombs of Gabal al-Mawta | Siwa | https://egymonuments.com/details/TombsofGabalal-Mawta
Finished — no more items.
all_sites: 94

In [4]:
df = pd.DataFrame(all_sites)
df

,place_name,place_location,photo_url,detail_link
0,Giza plateau,Giza,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/Pyramids
1,Egyptian Museum,Cairo,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/EgyptianMuseum
2,Sharm El Sheikh Museum,Sharm El Sheikh,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/SharmElSheikh...
3,Hurghada Museum,Hurghada,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/HurghadaMuseum
4,Luxor Temple,Luxor,https://egymonuments.com/storage/events/Septem...,https://egymonuments.com/details/LuxorTemple
...,...,...,...,...
89,Kafr al-Sheikh Museum,kafr el-shiekh,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/KafrElshaikh
90,Tanis (San al-Hagar),Al-Sharqia,https://egymonuments.com/storage/events/Septem...,https://egymonuments.com/details/Tanis%28Sanal...
91,Grand Egyptian Museum,Giza,https://egymonuments.com/storage/events/August...,https://visit-gem.com/
92,Temple of Aghurmi in Siwa,Siwa,https://egymonuments.com/storage/events/Januar...,https://egymonuments.com/details/TempleofAghur...
93,Tombs of Gabal al-Mawta,Siwa,https://egymonuments.com/storage/events/Januar...,https://egymonuments.com/details/TombsofGabala...

In [8]:
df["photo_url"][70]

'https://egymonuments.com/storage/events/July2024/8FxIOT4BiX273eJrG7Zb.png'

## Step 2

In [9]:
def extract_prices(container_selector):
    rows_out = []
    rows = driver.find_elements(By.CSS_SELECTOR, f"{container_selector} table tbody tr")
    for r in rows:
        tds = r.find_elements(By.TAG_NAME, "td")
        if len(tds) == 2:
            label = tds[0].text.strip()
            value = tds[1].text.strip().replace("\n", " ")
            if label:
                rows_out.append(f"{label}: {value}")
    return "\n".join(rows_out)


for idx, row in df.iterrows():
    link = row["detail_link"]
    if not link:
        continue

    print(f"[{idx + 1}/{len(df)}] Opening: {row['place_name']}")
    driver.get(link)

    try:
        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#pills-OtherNationality")))
        tickets_price_other = extract_prices("#pills-OtherNationality") or "Free"
    except (NoSuchElementException, TimeoutException):
        tickets_price_other = "Free"

    tickets_price_egyptian = "Not Available"
    try:
        egy_tab_btn = driver.find_element(By.CSS_SELECTOR, "#pills-Egyption-tab")
        driver.execute_script("arguments[0].click();", egy_tab_btn)
        wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, "#pills-Egyption")))
        tickets_price_egyptian = extract_prices("#pills-Egyption") or "Free"
    except NoSuchElementException:
        tickets_price_egyptian = "Not Available"

    try:
        hours_div = driver.find_element(By.XPATH, "//h3[contains(., 'OPENING HOURS')]/parent::div")
        opening_hours = hours_div.text.replace("OPENING HOURS", "").strip()
    except NoSuchElementException:
        opening_hours = "Not Available"

    try:
        booking_link = driver.find_element(By.CSS_SELECTOR, "a.btn-get-download").get_attribute("href")
    except NoSuchElementException:
        booking_link = ""

    # ---------- FREE ENTRY POLICY ----------
    free_entry_policy = "Not Available"
    try:
        cards = driver.find_elements(By.CSS_SELECTOR, "div.card.sdSlider")
        for card in cards:
            title_elem = card.find_element(By.CSS_SELECTOR, "h4.card-title")
            title_txt = driver.execute_script("return arguments[0].textContent;", title_elem).strip()
            if "FREE ENTRY POLICY" in title_txt.upper():
                text_elem = card.find_element(By.CSS_SELECTOR, "p.card-text")
                free_entry_policy = driver.execute_script("return arguments[0].textContent;", text_elem).strip()
                break
    except NoSuchElementException:
        pass

    df.at[idx, "tickets_price_other_nationality"] = tickets_price_other
    df.at[idx, "tickets_price_egyptian"] = tickets_price_egyptian
    df.at[idx, "opening_hours"] = opening_hours
    df.at[idx, "booking_link"] = booking_link
    df.at[idx, "free_entry_policy"] = free_entry_policy

driver.quit()
print("Done.")

[1/94] Opening: Giza plateau
[2/94] Opening: Egyptian Museum
[3/94] Opening: Sharm El Sheikh Museum
[4/94] Opening: Hurghada Museum
[5/94] Opening: Luxor Temple
[6/94] Opening: Karnak Temple
[7/94] Opening: Hatshepsut Temple
[8/94] Opening: Abu Simbel Temple
[9/94] Opening: Coptic Museum
[10/94] Opening: Dandarah Temple
[11/94] Opening: Deir El Madina
[12/94] Opening: Valley Of Kings
[13/94] Opening: Luxor Museum
[14/94] Opening: Esna Temple
[15/94] Opening: Salah Eldin Citadel
[16/94] Opening: Medinet Habu
[17/94] Opening: Philae Temple
[18/94] Opening: Kom Ombo Temple
[19/94] Opening: Mummification museum
[20/94] Opening: Ramesseum
[21/94] Opening: Saqqara Monuments
[22/94] Opening: The Temple Of Horus
[23/94] Opening: Tombs Of The Nobles
[24/94] Opening: Unfinished Obelisk
[25/94] Opening: Valley Of The Queens
[26/94] Opening: Islamic art museum
[27/94] Opening: Baron Empain Palace
[28/94] Opening: Nubia Museum
[29/94] Opening: Serapeum of Alexandria
[30/94] Opening: Catacombs
[31/94] Opening: Alexandria National Museum
[32/94] Opening: Qaitbay Citadel
[33/94] Opening: Ancient Roman Theatre
[34/94] Opening: Royal Jewellery Museum
[35/94] Opening: Carter House
[36/94] Opening: Mernpetah
[37/94] Opening: Deir El-shelwit
[38/94] Opening: Dahshur
[39/94] Opening: Memphis
[40/94] Opening: Prince Mohamed Aly Palace
[41/94] Opening: National Museum of Egyptian Civilization
[42/94] Opening: Royal Chariots Museum
[43/94] Opening: Graeco-Roman Museum
[44/94] Opening: Temple Of Amada
[45/94] Opening: Temple Of Wadi El-Sebua
[46/94] Opening: Temple of Kalabsha
[47/94] Opening: Elmoez street
[48/94] Opening: Bab Zuwaila
[49/94] Opening: House of suhaym
[50/94] Opening: Wasila Historical House
[51/94] Opening: House of al-Harawy
[52/94] Opening: Sabiel Nafesa Al-Bayda
[53/94] Opening: Gamal El-Din El-Zahabi house
[54/94] Opening: Al Ghuri Dome
[55/94] Opening: Wikala Of Al-Guri
[56/94] Opening: Gayer Anderson Museum
[57/94] Opening: Elkab Tombs
[58/94] Opening: Samaan Monastery
[59/94] Opening: Air Dome
[60/94] Opening: Elephantine Island
[61/94] Opening: Sehel Island
[62/94] Opening: The Pyramids of Meidum
[63/94] Opening: Fraser Tombs
[64/94] Opening: Zawyet Sultan
[65/94] Opening: Amarna
[66/94] Opening: Malawy Museum
[67/94] Opening: Meir Monumental Tombs
[68/94] Opening: El Hawawish
[69/94] Opening: Merit Amun Temple
[70/94] Opening: Sohag National Museum
[71/94] Opening: Sheikh Hamad Area
[72/94] Opening: Abydos Temple
[73/94] Opening: Shunet El Zebib
[74/94] Opening: Prince Youssef Palace
[75/94] Opening: Suez canal Museum
[76/94] Opening: Beni Hassan Tomb
[77/94] Opening: Mosque- Madrassa Sultan Hassan
[78/94] Opening: El Assasif
[79/94] Opening: Tomb of pabasa
[80/94] Opening: El-Tod Temple
[81/94] Opening: Al-Mualla Tombs
[82/94] Opening: Mut Temple
[83/94] Opening: Gebel al-Silsila
[84/94] Opening: Alhammamya Tombs
[85/94] Opening: Tuna el-Gebel
[86/94] Opening: Mary's Tree
[87/94] Opening: Al Matariyyah Obelisk
[88/94] Opening: Rawda Island Nilometer
[89/94] Opening: Rosetta City Monuments
[90/94] Opening: Kafr al-Sheikh Museum
[91/94] Opening: Tanis (San al-Hagar)
[92/94] Opening: Grand Egyptian Museum
[93/94] Opening: Temple of Aghurmi in Siwa
[94/94] Opening: Tombs of Gabal al-Mawta
Done.

In [11]:
df["booking_link"][93]

'https://egymonuments.com/book-date/259'

In [ ]:
df.to_csv("egymonuments_tickets.csv", index=False)

## Step 3 `on_map`

In [6]:
#import csv into df
df = pd.read_csv("egymonuments_tickets.csv")

In [7]:
df.head(10)

,place_name,place_location,photo_url,detail_link,tickets_price_other_nationality,tickets_price_egyptian,opening_hours,booking_link,free_entry_policy
0,Giza plateau,Giza,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/Pyramids,Adult: EGP 700\nStudent: EGP 350,Adult: EGP 60\nStudent: EGP 30,All Days\nSummer Working Hours:\nfrom 07:00 am...,https://egymonuments.com/book-date/2,Free entry for children below 6 years. ...
1,Egyptian Museum,Cairo,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/EgyptianMuseum,Adult: EGP 550\nStudent: EGP 275,Adult: EGP 30\nStudent: EGP 10,All Days\nSummer Working Hours:\nfrom 09:00 am...,https://egymonuments.com/book-date/3,Free entry for children below 6 years. ...
2,Sharm El Sheikh Museum,Sharm El Sheikh,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/SharmElSheikh...,Adult: EGP 200\nStudent: EGP 100,Adult: EGP 40\nStudent: EGP 20,All Days\nSummer Working Hours:\nfrom 10:00 am...,https://egymonuments.com/book-date/4,Free entry for children below 6 years. ...
3,Hurghada Museum,Hurghada,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/HurghadaMuseum,Adult: EGP 300\nStudent: EGP 150,Adult: EGP 80\nStudent: EGP 40,All Days\nSummer Working Hours:\nfrom 10:00 am...,https://egymonuments.com/book-date/5,Free entry for children below 6 years. ...
4,Luxor Temple,Luxor,https://egymonuments.com/storage/events/Septem...,https://egymonuments.com/details/LuxorTemple,Adult: EGP 500\nStudent: EGP 250,Adult: EGP 40\nStudent: EGP 20,All Days\nSummer Working Hours:\nfrom 06:00 am...,https://egymonuments.com/book-date/6,Free entry for children below 6 years. ...
5,Karnak Temple,Luxor,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/KarnakTemple,Adult: EGP 600\nStudent: EGP 300,Adult: EGP 40\nStudent: EGP 20,All Days\nSummer Working Hours:\nfrom 06:00 am...,https://egymonuments.com/book-date/7,Free entry for children below 6 years. ...
6,Hatshepsut Temple,Luxor,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/HatshepsutTemple,Adult: EGP 440\nStudent: EGP 220,Adult: EGP 40\nStudent: EGP 20,All Days\nSummer Working Hours:\nfrom 06:00 am...,https://egymonuments.com/book-date/8,Free entry for children below 6 years. ...
7,Abu Simbel Temple,Abu Simbel,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/AbuSimbelTemple,Adult: EGP 822\nStudent: EGP 445.5\nAdult: EGP...,Adult: EGP 30.5\nStudent: EGP 10.5\nAdult: EGP...,All Days\nSummer Working Hours:\nfrom 06:00 am...,https://egymonuments.com/book-date/9,Free entry for children below 6 years. ...
8,Coptic Museum,Cairo,https://egymonuments.com/storage/events/Septem...,https://egymonuments.com/details/CopticMuseum,Adult: EGP 280\nStudent: EGP 140,Adult: EGP 20\nStudent: EGP 10,All Days\nSummer Working Hours:\nfrom 09:00 am...,https://egymonuments.com/book-date/10,Free entry for children below 6 years. ...
9,Dandarah Temple,Qena,https://egymonuments.com/storage/events/Septem...,https://egymonuments.com/details/DandarahTemple,Adult: EGP 300\nStudent: EGP 150,Adult: EGP 20\nStudent: EGP 10,All Days\nSummer Working Hours:\nfrom 07:00 am...,https://egymonuments.com/book-date/11,Free entry for children below 6 years. ...

In [8]:
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Chrome(options=options)
wait = WebDriverWait(driver, 15)

for idx, row in df.iterrows():
    query = f"{row['place_name']}, {row['place_location']}, Egypt"
    print("Searching Maps for:", query)

    driver.get("https://www.google.com/maps/search/" + query.replace(" ", "+") + "?hl=en")

    try:
        WebDriverWait(driver, 15).until(
            lambda d: d.find_elements(By.CSS_SELECTOR, "h1.DUwDvf")
            or d.find_elements(By.CSS_SELECTOR, "div.Nv2PK")
        )
    except:
        pass

    if driver.find_elements(By.CSS_SELECTOR, "div.Nv2PK"):
        try:
            first_result = driver.find_element(By.CSS_SELECTOR, "div.Nv2PK a.hfpxzc")
            first_result.click()
            WebDriverWait(driver, 15).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, "h1.DUwDvf"))
            )
        except:
            pass

    time.sleep(1.5)

    df.at[idx, "on_map"] = driver.current_url

driver.quit()

Searching Maps for: Giza plateau, Giza, Egypt
Searching Maps for: Egyptian Museum, Cairo, Egypt
Searching Maps for: Sharm El Sheikh Museum, Sharm El Sheikh, Egypt
Searching Maps for: Hurghada Museum, Hurghada, Egypt
Searching Maps for: Luxor Temple, Luxor, Egypt
Searching Maps for: Karnak Temple, Luxor, Egypt
Searching Maps for: Hatshepsut Temple, Luxor, Egypt
Searching Maps for: Abu Simbel Temple, Abu Simbel, Egypt
Searching Maps for: Coptic Museum, Cairo, Egypt
Searching Maps for: Dandarah Temple, Qena, Egypt
Searching Maps for: Deir El Madina, Luxor, Egypt
Searching Maps for: Valley Of Kings, Luxor, Egypt
Searching Maps for: Luxor Museum, Luxor, Egypt
Searching Maps for: Esna Temple, Esna, Egypt
Searching Maps for: Salah Eldin Citadel, Cairo, Egypt
Searching Maps for: Medinet Habu, Luxor, Egypt
Searching Maps for: Philae Temple, Aswan, Egypt
Searching Maps for: Kom Ombo Temple, Aswan, Egypt
Searching Maps for: Mummification museum, Luxor, Egypt
Searching Maps for: Ramesseum, Luxor, Egypt
Searching Maps for: Saqqara Monuments, Giza, Egypt
Searching Maps for: The Temple Of Horus, Edfu, Egypt
Searching Maps for: Tombs Of The Nobles, Luxor, Egypt
Searching Maps for: Unfinished Obelisk, Aswan, Egypt
Searching Maps for: Valley Of The Queens, Luxor, Egypt
Searching Maps for: Islamic art museum, Cairo, Egypt
Searching Maps for: Baron Empain Palace, Cairo, Egypt
Searching Maps for: Nubia Museum, Aswan, Egypt
Searching Maps for: Serapeum of Alexandria, Alexandria, Egypt
Searching Maps for: Catacombs, Alexandria, Egypt
Searching Maps for: Alexandria National Museum, Alexandria, Egypt
Searching Maps for: Qaitbay Citadel, Alexandria, Egypt
Searching Maps for: Ancient Roman Theatre, Alexandria, Egypt
Searching Maps for: Royal Jewellery Museum, Alexandria, Egypt
Searching Maps for: Carter House, Luxor, Egypt
Searching Maps for: Mernpetah, Luxor, Egypt
Searching Maps for: Deir El-shelwit, Luxor, Egypt
Searching Maps for: Dahshur, Giza, Egypt
Searching Maps for: Memphis, Giza, Egypt
Searching Maps for: Prince Mohamed Aly Palace, Cairo, Egypt
Searching Maps for: National Museum of Egyptian Civilization, Cairo, Egypt
Searching Maps for: Royal Chariots Museum, Cairo, Egypt
Searching Maps for: Graeco-Roman Museum, Alexandria, Egypt
Searching Maps for: Temple Of Amada, Aswan, Egypt
Searching Maps for: Temple Of Wadi El-Sebua, Aswan, Egypt
Searching Maps for: Temple of Kalabsha, Aswan, Egypt
Searching Maps for: Elmoez street, Cairo, Egypt
Searching Maps for: Bab Zuwaila, Cairo, Egypt
Searching Maps for: House of suhaym, Cairo, Egypt
Searching Maps for: Wasila Historical House, Cairo, Egypt
Searching Maps for: House of al-Harawy, Cairo, Egypt
Searching Maps for: Sabiel Nafesa Al-Bayda, Cairo, Egypt
Searching Maps for: Gamal El-Din El-Zahabi house, Cairo, Egypt
Searching Maps for: Al Ghuri Dome, Cairo, Egypt
Searching Maps for: Wikala Of Al-Guri, Cairo, Egypt
Searching Maps for: Gayer Anderson Museum, Cairo, Egypt
Searching Maps for: Elkab Tombs, Aswan, Egypt
Searching Maps for: Samaan Monastery, Aswan, Egypt
Searching Maps for: Air Dome, Aswan, Egypt
Searching Maps for: Elephantine Island, Aswan, Egypt
Searching Maps for: Sehel Island, Aswan, Egypt
Searching Maps for: The Pyramids of Meidum, Beni Suef, Egypt
Searching Maps for: Fraser Tombs, Minya, Egypt
Searching Maps for: Zawyet Sultan, Minya, Egypt
Searching Maps for: Amarna, Minya, Egypt
Searching Maps for: Malawy Museum, Minya, Egypt
Searching Maps for: Meir Monumental Tombs, Assuit, Egypt
Searching Maps for: El Hawawish, Sohag, Egypt
Searching Maps for: Merit Amun Temple, Sohag, Egypt
Searching Maps for: Sohag National Museum, Sohag, Egypt
Searching Maps for: Sheikh Hamad Area, Sohag, Egypt
Searching Maps for: Abydos Temple, Sohag, Egypt
Searching Maps for: Shunet El Zebib, Sohag, Egypt
Searching Maps for: Prince Youssef Palace, Qena, Egypt
Searching Maps for: Suez canal Museum, Ismailia, Egypt
Searching Maps for: Beni Hassan Tomb, Minya, Egypt
Searching Maps for: Mosque- Madrassa Sultan Hassan, Cairo, Egypt
Searching Maps for: El Assasif, Luxor, Egypt
Searching Maps for: Tomb of pabasa, Luxor, Egypt
Searching Maps for: El-Tod Temple, Luxor, Egypt
Searching Maps for: Al-Mualla Tombs, Luxor, Egypt
Searching Maps for: Mut Temple, Luxor, Egypt
Searching Maps for: Gebel al-Silsila, Aswan, Egypt
Searching Maps for: Alhammamya Tombs, Assuit, Egypt
Searching Maps for: Tuna el-Gebel, Minya, Egypt
Searching Maps for: Mary's Tree, Cairo, Egypt
Searching Maps for: Al Matariyyah Obelisk, Cairo, Egypt
Searching Maps for: Rawda Island Nilometer, Cairo, Egypt
Searching Maps for: Rosetta City Monuments, El-bahira, Egypt
Searching Maps for: Kafr al-Sheikh Museum, kafr el-shiekh, Egypt
Searching Maps for: Tanis (San al-Hagar), Al-Sharqia, Egypt
Searching Maps for: Grand Egyptian Museum, Giza, Egypt
Searching Maps for: Temple of Aghurmi in Siwa, Siwa, Egypt
Searching Maps for: Tombs of Gabal al-Mawta, Siwa, Egypt

In [9]:
df

,place_name,place_location,photo_url,detail_link,tickets_price_other_nationality,tickets_price_egyptian,opening_hours,booking_link,free_entry_policy,on_map
0,Giza plateau,Giza,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/Pyramids,Adult: EGP 700\nStudent: EGP 350,Adult: EGP 60\nStudent: EGP 30,All Days\nSummer Working Hours:\nfrom 07:00 am...,https://egymonuments.com/book-date/2,Free entry for children below 6 years. ...,https://www.google.com/maps/search/Giza+platea...
1,Egyptian Museum,Cairo,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/EgyptianMuseum,Adult: EGP 550\nStudent: EGP 275,Adult: EGP 30\nStudent: EGP 10,All Days\nSummer Working Hours:\nfrom 09:00 am...,https://egymonuments.com/book-date/3,Free entry for children below 6 years. ...,https://www.google.com/maps/search/Egyptian+Mu...
2,Sharm El Sheikh Museum,Sharm El Sheikh,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/SharmElSheikh...,Adult: EGP 200\nStudent: EGP 100,Adult: EGP 40\nStudent: EGP 20,All Days\nSummer Working Hours:\nfrom 10:00 am...,https://egymonuments.com/book-date/4,Free entry for children below 6 years. ...,https://www.google.com/maps/search/Sharm+El+Sh...
3,Hurghada Museum,Hurghada,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/HurghadaMuseum,Adult: EGP 300\nStudent: EGP 150,Adult: EGP 80\nStudent: EGP 40,All Days\nSummer Working Hours:\nfrom 10:00 am...,https://egymonuments.com/book-date/5,Free entry for children below 6 years. ...,https://www.google.com/maps/search/Hurghada+Mu...
4,Luxor Temple,Luxor,https://egymonuments.com/storage/events/Septem...,https://egymonuments.com/details/LuxorTemple,Adult: EGP 500\nStudent: EGP 250,Adult: EGP 40\nStudent: EGP 20,All Days\nSummer Working Hours:\nfrom 06:00 am...,https://egymonuments.com/book-date/6,Free entry for children below 6 years. ...,https://www.google.com/maps/place/Luxor+Temple...
...,...,...,...,...,...,...,...,...,...,...
89,Kafr al-Sheikh Museum,kafr el-shiekh,https://egymonuments.com/storage/events/July20...,https://egymonuments.com/details/KafrElshaikh,Adult: EGP 220\nStudent: EGP 110,Adult: EGP 20\nStudent: EGP 10,Summer Working Hours:\nfrom 09:00 am Last Entr...,https://egymonuments.com/book-date/246,Free entry for children below 6 years. ...,https://www.google.com/maps/search/Kafr+al-She...
90,Tanis (San al-Hagar),Al-Sharqia,https://egymonuments.com/storage/events/Septem...,https://egymonuments.com/details/Tanis%28Sanal...,Adult: EGP 120\nStudent: EGP 60,Adult: EGP 10\nStudent: EGP 5,Summer Working Hours:\nfrom 09:00 am Last Entr...,https://egymonuments.com/book-date/249,Free entry for children below 6 years. ...,https://www.google.com/maps/search/Tanis+(San+...
91,Grand Egyptian Museum,Giza,https://egymonuments.com/storage/events/August...,https://visit-gem.com/,Free,Not Available,Not Available,NaN,Not Available,https://www.google.com/maps/search/Grand+Egypt...
92,Temple of Aghurmi in Siwa,Siwa,https://egymonuments.com/storage/events/Januar...,https://egymonuments.com/details/TempleofAghur...,Adult: EGP 120\nStudent: EGP 60,Adult: EGP 10\nStudent: EGP 5,All Days\nSummer Working Hours:\nfrom 09:00 am...,https://egymonuments.com/book-date/256,Free entry for children below 6 years. ...,https://www.google.com/maps/place/Amon+Temple/...
93,Tombs of Gabal al-Mawta,Siwa,https://egymonuments.com/storage/events/Januar...,https://egymonuments.com/details/TombsofGabala...,Adult: EGP 120\nStudent: EGP 60,Adult: EGP 10\nStudent: EGP 5,All Days\nSummer Working Hours:\nfrom 09:00 am...,https://egymonuments.com/book-date/259,Free entry for children below 6 years. ...,https://www.google.com/maps/search/Tombs+of+Ga...

In [10]:
df.to_csv("egymonuments_tickets.csv", index=False)